adx_contentsnippetid: d1446a51-f47d-f011-b4cb-000d3ae86fdc
adx_contentsnippetlanguageid: fba5eb7d-a87b-f011-b4cc-000d3ae86a1f
adx_display_name: Account Settings Text in FR
adx_name: GCWeb/App/AccountSettingsText
adx_type: 756150000
