adx_contentsnippetid: 053dc730-f47d-f011-b4cb-000d3ae86fdc
adx_contentsnippetlanguageid: 479653ed-6561-4160-a081-e917bb73b148
adx_display_name: Account Settings Text in EN
adx_name: GCWeb/App/AccountSettingsText
adx_type: 756150000
